kind: Deployment
apiVersion: apps/v1
metadata:
  name: nfs-provisioner
spec:
  selector:
    matchLabels:
      app: nfs-provisioner
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nfs-provisioner
    spec:
      # The following toleration and nodeSelector will place the nfs provisioner on the ICP master node
      tolerations:
      - key: node-role.kubernetes.io/etcd
        operator: Equal
        value: "true"
        effect: NoExecute
      - key: node-role.kubernetes.io/controlplane
        operator: Equal
        value: "true"
        effect: NoSchedule
      nodeSelector:
        node-role.kubernetes.io/controlplane: "true"
      serviceAccount: nfs-provisioner
      containers:
        - name: nfs-provisioner
          image: quay.io/kubernetes_incubator/nfs-provisioner:v2.2.2 # 1.0.8
          ports:
            - name: nfs
              containerPort: 2049
            - name: mountd
              containerPort: 20048
            - name: rpcbind
              containerPort: 111
            - name: rpcbind-udp
              containerPort: 111
              protocol: UDP
          securityContext:
            capabilities:
              add:
                - DAC_READ_SEARCH
                - SYS_RESOURCE
          args:
            - "-provisioner=quay.io/nfs-provisioner"
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: SERVICE_NAME
              value: nfs-provisioner
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
          - name: export-volume
            mountPath: /export
          resources:
            limits:
              cpu: 1000m
              memory: 500Mi
      volumes:
      - name: export-volume
        hostPath:
          path: /storage/dynamic