apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - prometheus/service.yaml
  - prometheus/configmap.yaml
  - prometheus/statefulset.yaml

  - grafana/secret.yaml
  - grafana/ingress.yaml
  - grafana/service.yaml
  - grafana/configmap.yaml
  - grafana/statefulset.yaml