# Adds namespace to all resources.
namespace: kube-system

resources:
- traefik-service-account.yaml
- traefik-config-map.yaml
- traefik-deployment.yaml
- traefik-pvc.yaml
- traefik-rbac.yaml
- traefik-service.yaml
