apiVersion: v1
kind: Service
metadata:
  name: traefik-ingress-lb
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    - port: 443
      targetPort: 443
      protocol: TCP
      name: https
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: traefik
  selector:
    k8s-app: traefik-ingress-lb
  type: LoadBalancer