apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-acme
  labels:
    storage-group: traefik
  annotations:
    volume.alpha.kubernetes.io/storage-class: fast
spec:
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 0.5Gi
